# Generated by Django 2.2.1 on 2019-05-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20190511_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amountRaised',
            field=models.BinaryField(blank=True, max_length=100, verbose_name='amountRaised'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignTitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='campaignTitle'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='currencyType',
            field=models.BinaryField(blank=True, max_length=100, verbose_name='currencyType'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='endDate',
            field=models.CharField(blank=True, max_length=100, verbose_name='endDate'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='numberContributors',
            field=models.BinaryField(blank=True, max_length=100, verbose_name='numberContributors'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.BinaryField(blank=True, max_length=200),
        ),
    ]
