# Generated by Django 2.2.1 on 2019-05-14 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20190511_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amountRaised',
            field=models.CharField(blank=True, max_length=100, verbose_name='amountRaised'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='currencyType',
            field=models.CharField(blank=True, max_length=100, verbose_name='currencyType'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='numberContributors',
            field=models.CharField(blank=True, max_length=100, verbose_name='numberContributors'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Category')),
            ],
        ),
    ]
